id = "jemini-theme"
name = "Jemini"
version = "0.0.1"
schema_version = 1
authors = ["guba <gubacoolest@gmail.com>"]
description = "A port of Google Gemini color scheme"
repository = "https://github.com/iamguba/zed-jemini-theme"
